<?php

namespace App\Filament\Resources\Forms\Pages;

use App\Filament\Resources\Forms\FormResource;
use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Log;

class EditForm extends EditRecord
{
    protected static string $resource = FormResource::class;

    protected function mutateFormDataBeforeSave(array $data): array
    {
        Log::info(json_encode($data, JSON_THROW_ON_ERROR));
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub

    }

    protected function getHeaderActions(): array
    {
        return [
            DeleteAction::make(),
        ];
    }
}
